# Generated by Django 4.2.7 on 2023-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_remove_demand_user_remove_purchase_drug_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='drug',
        ),
        migrations.AddField(
            model_name='purchase',
            name='drug_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
